version: '3.0'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:5.4.0
    volumes:
      - ./logstash/pipeline/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch
    networks:
      - elastic-stack

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
      - 9200:9200
    networks:
      - elastic-stack

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    ports: 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic-stack

networks:
  elastic-stack:
    driver: bridge